# Generated by Django 3.2.6 on 2021-08-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonuser',
            name='dog',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
